### ISSUE TITLE
Dead Kernel error when I try to run the ffa_search function

### ISSUE THREAD

**Issue by ReshmaAnnaThomas** [v-morello/riptide#3]
I was trying to run riptide on a jupyter notebook following the exact same code as given in the Documentation page (under Quickstart guide). The jupyter kernel dies as soon as I run the ffa_search function. It'd be great if you could help fix this! Attaching a screenshot of the error. 
<img width="930" alt="Screen Shot 2022-09-08 at 3 02 56 PM" src="https://user-images.githubusercontent.com/56050319/189205742-f9b0b926-3b0f-44ac-a4a7-d277249fcf3f.png">

**Comment by v-morello** [comment]
Hi @ReshmaAnnaThomas,
I'm going to need considerably more information here. What OS are you on ? What version of python are you using ? How did you install riptide ? What version are you running ? Could you please run the unit tests and check the result ?

```python
import riptide
print(riptide.__version__)
riptide.test()
```

This looks like a segmentation fault on the C++ side, which is quite surprising here.

**Comment by v-morello** [comment]
@ReshmaAnnaThomas I haven't heard from you in a while, are you still having trouble or did you find a solution ?

**Comment by v-morello** [comment]
@ReshmaAnnaThomas Any news to report, or should I close this ? I'm curious to find out if there is indeed a bug somewhere :smile:

**Comment by ReshmaAnnaThomas** [comment]
I'm sorry for not responding earlier. I was trying to see if it was something wrong with the system here. Riptide worked perfectly in a node which had more RAM and for the other nodes, it maxed out. So I think it's a local issue. I think you can close the issue. Sorry about this!

**Comment by v-morello** [comment]
No worries, closing this then.
